version: '3'
services:
    webserver:
        build: ./webserver7/
        volumes:
            - ../:/var/www
            - ./webserver7/config/php.ini:/usr/local/etc/php/php.ini
        ports:
            - 80:80
        working_dir: /var/www
        container_name: webserver-eata-local
